FROM python:3.12-slim-bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    make

COPY . /opt/gamewinner
WORKDIR /opt/gamewinner

RUN make install
ENTRYPOINT ["make", "test"]