name: gamewinner build and test
run-name: ${{ github.actor }} running CI for gamewinner
on: [push]
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: build & test
        run: |
          make install
          make precommit
          make mypy
          make test
      - name: Store bracket results
        uses: actions/upload-artifact@v4
        with:
          name: brackets
          path: generated/*.bkt
